Unit2Project/Models/Comic.cs
using System.ComponentModel.DataAnnotations;


// This is the Comic class that helps creates the Comics
namespace Unit2Project.Models
{
    
    public class Comic
    {
        [Key]
        public int? ComicId { get; set; }
        [Required(ErrorMessage = "Please enter a name.")]
        public string? Name { get; set; }
        [Required(ErrorMessage = "Please enter a Company Name.")]
        public string? Company { get; set; }

        [Required(ErrorMessage = "Please enter an issue number.")]
        public int? IssueNo { get; set; }

       
        
    }
}

Unit2Project/Models/ComicContext.cs
using Microsoft.EntityFrameworkCore;


// This is the Comic Context class that stores it in like a database
namespace Unit2Project.Models
{
    public class ComicContext : DbContext
    {
        public ComicContext() { }

        public ComicContext(DbContextOptions<ComicContext> options)
            : base(options)
        { }

        public DbSet<Comic> Comics { get; set; }
        

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Comic>().HasData(
                new Comic
                {
                    ComicId = 1,
                    Name = "Absolute Carnage ",
                    Company = "Marvel ",
                    IssueNo = 1,
                },
                new Comic
                {
                    ComicId = 2,
                    Name = "Batman: Year One ",
                    Company = "D.C. ",
                    IssueNo = 1,
                },
                new Comic
                {
                    ComicId = 3,
                    Name = "Invincible ",
                    Company = "Image Comics ",
                    IssueNo = 1,
                });

            
        }
    }
}

Unit2Project/Controllers/ComicController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics.Eventing.Reader;
using Unit2Project.Models;

// This is the Comic Controller that controlls the edit add and delete Views. 
// It also gets the data from the ComicContext class 

namespace Unit2Project.Controllers
{
    public class ComicController : Controller
    {
        private ComicContext context { get; set; }

        public ComicController(ComicContext ctx)
        {
            context = ctx;
        }

        [HttpGet]
        public IActionResult Add() 
        {
            ViewBag.Action = "Add";
            return View("Edit", new Comic());
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewBag.Action = "Edit";
            var comic = context.Comics.Find(id);
            return View(comic);
        }

        [HttpPost]
        public IActionResult Edit(Comic comic) 
        {
            if (ModelState.IsValid)
            {
                if(comic.ComicId == 0)
                    context.Comics.Add(comic);
                else
                    context.Comics.Update(comic);
                context.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewBag.Action = (comic.ComicId == 0) ? "Add" : "Edit";
                return View(comic);
            }
            
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var comic = context.Comics.Find(id);
            return View(comic);
        }
        [HttpPost]
        public IActionResult Delete(Comic comic) 
        {
            context.Comics.Remove(comic);
            context.SaveChanges();
            return RedirectToAction("Index", "Home");
        }
    }
}

Unit2Project/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using Unit2Project.Models;

// This is the Home Controller that controls the Index page

namespace Unit2Project.Controllers
{
    public class HomeController : Controller
    {
        private ComicContext context { get; set; }

        public HomeController(ComicContext ctx) 
        {
            context = ctx;
        } 
        public IActionResult Index()
        {
            var comics = context.Comics.ToList();
            return View(comics);
        }
    }
}

Unit2Project/Views/Comic/Delete.cshtml
@model Comic
@{
    ViewBag.Title = "Delete Comic";
}
<!--
    This is the Delete Page that deletes the comics you want to get rid of
-->
<!DOCTYPE html>
<html>
    <head>
        <title>Delete</title>
    </head>
<body>
    <h2>Confirm Deleteion</h2>
    <h3>@Model.Name (@Model.Company)</h3>

    <form asp-action="Delete" method="post">
        <input type="hidden" asp-for="ComicId" />

        <button type="submit" class="btn btn-primary">Delete</button>
        <a asp-controller="Home" asp-action="Index"
                calss="btn btn-primary">Go Back</a>
    </form>
</body>
</html>

Unit2Project/Views/Comic/Edit.cshtml
@model Comic
@{
    string title = ViewBag.Action + " Comic";
    ViewBag.Title = title;
}

<!--
    This is the Edit Page, you can edit your comics here
-->
<!DOCTYPE html>
<html>
    
 <body>
     <h2>@ViewBag.Title</h2>

     <form asp-action="Edit" method="post">
         <div asp-validation-summary="All" class="text-danger"></div>

         <div class="form-group">
             <label asp-for="Name">Name</label>
             <input asp-for="Name" class="form-control" />
         </div>
         <br />
        <div class="form-group">
             <lable asp-for="Company">Company</lable>
             <input asp-for="Company" class="form-control" />
         </div>
         <br />
         <div class="form-group">
             <label asp-for="IssueNo">Issue Number</label>
             <input asp-for="IssueNo" class="form-control" />
         </div>

         <input type="hidden" asp-for="ComicId" />

         <button type="submit" class="btn btn-primary">@ViewBag.Action</button>
         <a asp-controller="Home" asp-action="Index"
                class="btn btn-primary">Go Back</a>
     </form>
 </body>
</html>

Unit2Project/Views/Home/Index.cshtml
@model List<Comic>
@{
    ViewBag.Title = "Comics Database";
}

<!--
    This is the Home site to view your comics
-->

<!DOCTYPE html>
<html>
 <head>
     <title>Home</title>
 </head>
 <body>
    <h2>Welcome Please Enter Your Comics</h2>

   
    <table class="maintable">
        <thead>
            <tr>
                <th class="Name">Name</th>
                <th class="Company">Company</th>
                <th class="Issue">Issue Number</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var comic in Model)
            {
                <tr>
                    <td>@comic.Name</td>
                    <td>@comic.Company</td>
                    <td>@comic.IssueNo</td>
                    <td>
                        <a asp-controller="Comic" asp-action="Edit"
                            asp-route-id="@comic.ComicId">Edit</a>
                            <a asp-controller="Comic" asp-action="Delete"
                            asp-route-id="@comic.ComicId">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
        <a asp-controller="Comic" asp-action="Add">Add Comics</a>
</body>
</html>

Unit2Project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <link rel="stylesheet" type="text/css"
              href="~/lib/bootstrap/css/MyCustom.css" />
    </head>
@RenderBody()
</html>
   